name: CI

on:
  push:
    branches: ['**']

permissions:
  contents: read

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Install dependencies
        run: |
          if [ ! -f package-lock.json ]; then
            npm install
          else
            npm ci || (echo 'npm ci failed, retrying with clean install' && rm -rf node_modules package-lock.json && npm install)
          fi

      - name: Run ESLint
        run: npm run lint

      - name: Run Vitest
        run: npx vitest run --reporter=default
